require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoordinatesController do

  # This should return the minimal set of attributes required to create a valid
  # Coordinate. As you add validations to Coordinate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "longitude" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoordinatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coordinates as @coordinates" do
      coordinate = Coordinate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coordinates).should eq([coordinate])
    end
  end

  describe "GET show" do
    it "assigns the requested coordinate as @coordinate" do
      coordinate = Coordinate.create! valid_attributes
      get :show, {:id => coordinate.to_param}, valid_session
      assigns(:coordinate).should eq(coordinate)
    end
  end

  describe "GET new" do
    it "assigns a new coordinate as @coordinate" do
      get :new, {}, valid_session
      assigns(:coordinate).should be_a_new(Coordinate)
    end
  end

  describe "GET edit" do
    it "assigns the requested coordinate as @coordinate" do
      coordinate = Coordinate.create! valid_attributes
      get :edit, {:id => coordinate.to_param}, valid_session
      assigns(:coordinate).should eq(coordinate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coordinate" do
        expect {
          post :create, {:coordinate => valid_attributes}, valid_session
        }.to change(Coordinate, :count).by(1)
      end

      it "assigns a newly created coordinate as @coordinate" do
        post :create, {:coordinate => valid_attributes}, valid_session
        assigns(:coordinate).should be_a(Coordinate)
        assigns(:coordinate).should be_persisted
      end

      it "redirects to the created coordinate" do
        post :create, {:coordinate => valid_attributes}, valid_session
        response.should redirect_to(Coordinate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coordinate as @coordinate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coordinate.any_instance.stub(:save).and_return(false)
        post :create, {:coordinate => { "longitude" => "invalid value" }}, valid_session
        assigns(:coordinate).should be_a_new(Coordinate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coordinate.any_instance.stub(:save).and_return(false)
        post :create, {:coordinate => { "longitude" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coordinate" do
        coordinate = Coordinate.create! valid_attributes
        # Assuming there are no other coordinates in the database, this
        # specifies that the Coordinate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Coordinate.any_instance.should_receive(:update).with({ "longitude" => "1" })
        put :update, {:id => coordinate.to_param, :coordinate => { "longitude" => "1" }}, valid_session
      end

      it "assigns the requested coordinate as @coordinate" do
        coordinate = Coordinate.create! valid_attributes
        put :update, {:id => coordinate.to_param, :coordinate => valid_attributes}, valid_session
        assigns(:coordinate).should eq(coordinate)
      end

      it "redirects to the coordinate" do
        coordinate = Coordinate.create! valid_attributes
        put :update, {:id => coordinate.to_param, :coordinate => valid_attributes}, valid_session
        response.should redirect_to(coordinate)
      end
    end

    describe "with invalid params" do
      it "assigns the coordinate as @coordinate" do
        coordinate = Coordinate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coordinate.any_instance.stub(:save).and_return(false)
        put :update, {:id => coordinate.to_param, :coordinate => { "longitude" => "invalid value" }}, valid_session
        assigns(:coordinate).should eq(coordinate)
      end

      it "re-renders the 'edit' template" do
        coordinate = Coordinate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coordinate.any_instance.stub(:save).and_return(false)
        put :update, {:id => coordinate.to_param, :coordinate => { "longitude" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coordinate" do
      coordinate = Coordinate.create! valid_attributes
      expect {
        delete :destroy, {:id => coordinate.to_param}, valid_session
      }.to change(Coordinate, :count).by(-1)
    end

    it "redirects to the coordinates list" do
      coordinate = Coordinate.create! valid_attributes
      delete :destroy, {:id => coordinate.to_param}, valid_session
      response.should redirect_to(coordinates_url)
    end
  end

end
