require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocationRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # LocationRequest. As you add validations to LocationRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocationRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all location_requests as @location_requests" do
      location_request = LocationRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:location_requests).should eq([location_request])
    end
  end

  describe "GET show" do
    it "assigns the requested location_request as @location_request" do
      location_request = LocationRequest.create! valid_attributes
      get :show, {:id => location_request.to_param}, valid_session
      assigns(:location_request).should eq(location_request)
    end
  end

  describe "GET new" do
    it "assigns a new location_request as @location_request" do
      get :new, {}, valid_session
      assigns(:location_request).should be_a_new(LocationRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested location_request as @location_request" do
      location_request = LocationRequest.create! valid_attributes
      get :edit, {:id => location_request.to_param}, valid_session
      assigns(:location_request).should eq(location_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LocationRequest" do
        expect {
          post :create, {:location_request => valid_attributes}, valid_session
        }.to change(LocationRequest, :count).by(1)
      end

      it "assigns a newly created location_request as @location_request" do
        post :create, {:location_request => valid_attributes}, valid_session
        assigns(:location_request).should be_a(LocationRequest)
        assigns(:location_request).should be_persisted
      end

      it "redirects to the created location_request" do
        post :create, {:location_request => valid_attributes}, valid_session
        response.should redirect_to(LocationRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved location_request as @location_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocationRequest.any_instance.stub(:save).and_return(false)
        post :create, {:location_request => { "user_id" => "invalid value" }}, valid_session
        assigns(:location_request).should be_a_new(LocationRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocationRequest.any_instance.stub(:save).and_return(false)
        post :create, {:location_request => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested location_request" do
        location_request = LocationRequest.create! valid_attributes
        # Assuming there are no other location_requests in the database, this
        # specifies that the LocationRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LocationRequest.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => location_request.to_param, :location_request => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested location_request as @location_request" do
        location_request = LocationRequest.create! valid_attributes
        put :update, {:id => location_request.to_param, :location_request => valid_attributes}, valid_session
        assigns(:location_request).should eq(location_request)
      end

      it "redirects to the location_request" do
        location_request = LocationRequest.create! valid_attributes
        put :update, {:id => location_request.to_param, :location_request => valid_attributes}, valid_session
        response.should redirect_to(location_request)
      end
    end

    describe "with invalid params" do
      it "assigns the location_request as @location_request" do
        location_request = LocationRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocationRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => location_request.to_param, :location_request => { "user_id" => "invalid value" }}, valid_session
        assigns(:location_request).should eq(location_request)
      end

      it "re-renders the 'edit' template" do
        location_request = LocationRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocationRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => location_request.to_param, :location_request => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested location_request" do
      location_request = LocationRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => location_request.to_param}, valid_session
      }.to change(LocationRequest, :count).by(-1)
    end

    it "redirects to the location_requests list" do
      location_request = LocationRequest.create! valid_attributes
      delete :destroy, {:id => location_request.to_param}, valid_session
      response.should redirect_to(location_requests_url)
    end
  end

end
